#import "./tagFragment.gql"

query filterTagsQuery($shopId: ID!) {
  filterTags(shopId: $shopId) {
    filterTags {
      tag {
        ...TagInfo
      }
      subTags {
        ...TagInfo
      }
    }
  }
}
